name: Distribute To Development

on:
  push:
    branches: [ development ]

jobs:
  android-distribute-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Cache Ruby - Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Grant Permission to Execute
        run: cd android && chmod +x gradlew

      - name: Install fastlane, plugins, bundler
        run: |
          cd android
          gem install fastlane
          fastlane add_plugin firebase_app_distribution
          gem install bundler:2.1.4
          bundle install --jobs 4 --retry 3
          bundle update --bundler
          bundle config path vendor/bundle

      - name: Update fastlane and plugins
        run: |
          cd android
          fastlane update_fastlane
          fastlane update_plugins
      
      - name: Install node modules
        run: npm install

      - name: Deploy Development Debug APK to Firebase App Distribution
        run: cd android && fastlane buildDev
        env:
          # PLAY_STORE_CREDENTIALS: ${{ secrets.PLAY_STORE_CREDENTIALS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          FIREBASE_APP_ID_DEV: ${{ secrets.FIREBASE_APP_ID_DEV }}
          # FIREBASE_APP_ID_STAGING: ${{ secrets.FIREBASE_APP_ID_STAGING }}
          # FIREBASE_APP_ID_PROD: ${{ secrets.FIREBASE_APP_ID_PROD }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          # FIREBASE_TESTER_GROUPS_DEV: android/FirebaseAppDistributionConfig/groups.txt
          # FIREBASE_RELEASE_NOTES_DEV: android/FirebaseAppDistributionConfig/release_notes_dev.txt
          # FIREBASE_TESTER_GROUPS: android/FirebaseAppDistributionConfig/groups.txt
          # FIREBASE_RELEASE_NOTES: android/FirebaseAppDistributionConfig/release_notes.txt
